### ISSUE TITLE
Add the dialogs

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#237]
### Description
Add the new design for all dialogs

### Tasks
- [X] Design
- [x] Implement transfer dialog
- [x] Implement quick connect dialog
- [x] Implement open channel dialog
- [x] Implement deposit / withdraw dialog
- [x] Implement register token dialog
- [x] Implement add / edit contact dialog
- [x] Implement  confirmation dialogs
