### ISSUE TITLE
Restructure header

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#250]
### Description
There are several improvements we want to make to the header

### Tasks
- [x] Ether balance should be less prominent
- [x] New flow for Top up button
- [x] Rename Top up button
- [x] Extract QR icon button + relocation
- [x] Extract and redesign user data (including address)
- [x] Implement
