### ISSUE TITLE
Test prototype

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#331]
### Description
Send the prototype to test users for gathering feedback

### Tasks
- [x] build test package
- [x] write questions for the feedback
- [x] conduct user tests
- [x] read through feedback and decide on actions

**Comment by sashseurat** [comment]
questionnaire is being drafted here:
https://docs.google.com/forms/d/1KA4jqAW3pxFb5oButWRNnuHNXidBAnsg_hunY0vFA60/edit
