### ISSUE TITLE
Channels too prominent

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#349]
### Description
The user should not have to care about channels, as it is the goal of Raiden that they are be able to send (mediated) transfers to anyone as long as they have any open channel. For making it easy for new user to start, it would be nice to abstract away the channels.

For now it might be a first step to have the channels on a separate page.

### Tasks
- [x] Design new home page without channels
- [x] Implement new home page without channels
- [x] Design new channels page
- [x] Implement new channels page
